export const statistics = {
  rating: 4.9,

  totalFeedback: 1248,

  positive: 98,

  responseTime: 24,

  totalRespondent: 1248,

  trend: [
    {
      month: "Jan 2026",
      score: 4.20,
      verySatisfied: 10,
      satisfied: 20,
      fairlySatisfied: 45,
      lessSatisfied: 25,
      respondent: 1000,
      category: "Kurang Puas",
      color: "#EF4444",
    },
    {
      month: "Feb 2026",
      score: 4.28,
      verySatisfied: 12,
      satisfied: 18,
      fairlySatisfied: 40,
      lessSatisfied: 30,
      respondent: 1050,
      category: "Kurang Puas",
      color: "#EF4444",
    },
    {
      month: "Mar 2026",
      score: 4.38,
      verySatisfied: 15,
      satisfied: 20,
      fairlySatisfied: 36,
      lessSatisfied: 29,
      respondent: 1100,
      category: "Cukup Puas",
      color: "#FACC15",
    },
    {
      month: "Apr 2026",
      score: 4.52,
      verySatisfied: 20,
      satisfied: 25,
      fairlySatisfied: 30,
      lessSatisfied: 25,
      respondent: 1200,
      category: "Puas",
      color: "#2563EB",
    },
    {
      month: "Mei 2026",
      score: 4.61,
      verySatisfied: 30,
      satisfied: 30,
      fairlySatisfied: 25,
      lessSatisfied: 15,
      respondent: 1250,
      category: "Puas",
      color: "#2563EB",
    },
    {
      month: "Jun 2026",
      score: 4.76,
      verySatisfied: 35,
      satisfied: 31,
      fairlySatisfied: 20,
      lessSatisfied: 14,
      respondent: 1300,
      category: "Puas",
      color: "#2563EB",
    },
    {
      month: "Jul 2026",
      score: 4.82,
      verySatisfied: 33,
      satisfied: 32,
      fairlySatisfied: 22,
      lessSatisfied: 13,
      respondent: 1350,
      category: "Sangat Puas",
      color: "#22C55E",
    },
    {
      month: "Agu 2026",
      score: 4.86,
      verySatisfied: 28,
      satisfied: 29,
      fairlySatisfied: 28,
      lessSatisfied: 15,
      respondent: 1400,
      category: "Sangat Puas",
      color: "#22C55E",
    },
    {
      month: "Sep 2026",
      score: 4.88,
      verySatisfied: 25,
      satisfied: 27,
      fairlySatisfied: 30,
      lessSatisfied: 18,
      respondent: 1500,
      category: "Sangat Puas",
      color: "#22C55E",
    },
    {
      month: "Okt 2026",
      score: 4.92,
      verySatisfied: 20,
      satisfied: 25,
      fairlySatisfied: 40,
      lessSatisfied: 15,
      respondent: 1500,
      category: "Sangat Puas",
      color: "#22C55E",
    },
    {
      month: "Nov 2026",
      score: 4.95,
      verySatisfied: 18,
      satisfied: 27,
      fairlySatisfied: 42,
      lessSatisfied: 13,
      respondent: 1600,
      category: "Sangat Puas",
      color: "#22C55E",
    },
    {
      month: "Des 2026",
      score: 4.98,
      verySatisfied: 22,
      satisfied: 30,
      fairlySatisfied: 35,
      lessSatisfied: 13,
      respondent: 1650,
      category: "Sangat Puas",
      color: "#22C55E",
    },
  ],

  composition: [
    {
      label: "Sangat Puas",
      value: 72,
      color: "#22C55E",
      change: 5,
    },
    {
      label: "Puas",
      value: 20,
      color: "#2563EB",
      change: -2,
    },
    {
      label: "Cukup Puas",
      value: 6,
      color: "#FACC15",
      change: -1,
    },
    {
      label: "Kurang Puas",
      value: 2,
      color: "#EF4444",
      change: -2,
    },
  ],
};